// WhatsApp channel — Baileys local-session backend.
// CareerOS owns a single shared WA number. Users connect via CONNECT-{token} deep link
// generated by Settings → Channels, identical flow to the Telegram /start TOKEN command.

import makeWASocket, { DisconnectReason, useMultiFileAuthState, type WASocket } from '@whiskeysockets/baileys'
import { Boom } from '@hapi/boom'
import { eq, and } from 'drizzle-orm'
import { db, schema } from '../db/index.js'
import { conversationService } from '../services/index.js'
import { config } from '../config.js'

let _sock: WASocket | null = null

function jidToPhone(jid: string): string {
  return jid.split('@')[0]
}

export async function sendWhatsAppMessage(to: string, text: string): Promise<void> {
  if (!_sock) {
    console.log(`[whatsapp] no active session — message not sent to ${to}`)
    return
  }
  const jid = to.includes('@') ? to : `${to}@s.whatsapp.net`
  await _sock.sendMessage(jid, { text })
}

async function handleWhatsAppMessage(jid: string, body: string): Promise<void> {
  const phone = jidToPhone(jid)

  // Account linking: message body is "CONNECT-{token}"
  if (body.startsWith('CONNECT-')) {
    const token = body.slice('CONNECT-'.length).trim()
    const now = new Date()

    const [linkToken] = await db
      .select()
      .from(schema.channelLinkTokens)
      .where(eq(schema.channelLinkTokens.token, token))
      .limit(1)

    if (!linkToken) {
      await sendWhatsAppMessage(phone, 'Invalid connection link. Please generate a new one from CareerOS Settings → Channels.')
      return
    }
    if (linkToken.usedAt) {
      await sendWhatsAppMessage(phone, 'This link has already been used. Generate a new one from CareerOS Settings → Channels.')
      return
    }
    if (now > linkToken.expiresAt) {
      await sendWhatsAppMessage(phone, 'This link has expired. Generate a new one from CareerOS Settings → Channels.')
      return
    }

    await db.update(schema.users).set({ whatsappNumber: phone }).where(eq(schema.users.id, linkToken.userId))
    await db.update(schema.channelLinkTokens).set({ usedAt: now }).where(eq(schema.channelLinkTokens.id, linkToken.id))

    const [existingConfig] = await db
      .select({ id: schema.channelConfigs.id })
      .from(schema.channelConfigs)
      .where(and(eq(schema.channelConfigs.userId, linkToken.userId), eq(schema.channelConfigs.channel, 'whatsapp')))
      .limit(1)

    const configData = { wa_number: phone }
    if (existingConfig) {
      await db
        .update(schema.channelConfigs)
        .set({ status: 'connected', config: configData, enabled: true, lastCheckedAt: now })
        .where(eq(schema.channelConfigs.id, existingConfig.id))
    } else {
      await db.insert(schema.channelConfigs).values({
        userId: linkToken.userId,
        channel: 'whatsapp',
        status: 'connected',
        config: configData,
        enabled: true,
        lastCheckedAt: now,
      })
    }

    await sendWhatsAppMessage(
      phone,
      'Welcome to CareerOS!\n\nYour account is linked. You can now:\n• Send a job URL to analyze it\n• Ask career questions\n• Request resume tailoring\n• Receive agent updates',
    )
    return
  }

  // Regular message: resolve user by stored phone number
  const [user] = await db
    .select()
    .from(schema.users)
    .where(eq(schema.users.whatsappNumber, phone))
    .limit(1)

  if (!user) {
    await sendWhatsAppMessage(
      phone,
      'Your WhatsApp number is not linked to CareerOS yet.\n\nOpen CareerOS Settings → Channels and click "Connect WhatsApp" to get started.',
    )
    return
  }

  try {
    const response = await conversationService.handleMessage(user.id, 'whatsapp', body, undefined, phone)
    let replyText = response.response
    if (response.pendingApproval) {
      replyText += '\n\nReply with "approve" or "reject" to proceed.'
    }
    await sendWhatsAppMessage(phone, replyText)
  } catch (err) {
    console.error('[whatsapp] conversationService error:', err)
    await sendWhatsAppMessage(phone, 'Sorry, something went wrong. Please try again in a moment.')
  }
}

export async function startWhatsappBot(): Promise<void> {
  const { state, saveCreds } = await useMultiFileAuthState(config.whatsappSessionPath)

  const sock = makeWASocket({
    auth: state,
    printQRInTerminal: true,
  })

  _sock = sock

  sock.ev.on('creds.update', saveCreds)

  sock.ev.on('connection.update', ({ connection, lastDisconnect }) => {
    if (connection === 'close') {
      const statusCode = (lastDisconnect?.error as Boom)?.output?.statusCode
      const shouldReconnect = statusCode !== DisconnectReason.loggedOut
      console.log(`[whatsapp] connection closed (status ${statusCode}), reconnecting: ${shouldReconnect}`)
      _sock = null
      if (shouldReconnect) {
        startWhatsappBot().catch(err => console.error('[whatsapp] reconnect failed:', err))
      } else {
        console.log('[whatsapp] logged out — scan QR to re-authenticate')
      }
    } else if (connection === 'open') {
      console.log('[whatsapp] connected')
    }
  })

  sock.ev.on('messages.upsert', ({ messages, type }) => {
    if (type !== 'notify') return
    void (async () => {
      for (const msg of messages) {
        if (msg.key.fromMe) continue
        const jid = msg.key.remoteJid
        if (!jid || jid.endsWith('@g.us')) continue // skip group messages
        const body =
          msg.message?.conversation ??
          msg.message?.extendedTextMessage?.text ??
          ''
        if (body) {
          await handleWhatsAppMessage(jid, body).catch(err =>
            console.error('[whatsapp] message handler error:', err),
          )
        }
      }
    })()
  })
}
